version: '3.6'

x-common-postgres-variables: &common-postgres-variables
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: mysecretpassword
  
x-common-influx-variables: &common-influx-variables
  INFLUXDB_DB: smart_factory
  INFLUXDB_USER: admin
  INFLUXDB_USER_PASSWORD: admin

services:
  grafana:
    build: ./grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_plugins:/var/lib/grafana/plugins
      - grafana_provisioning:/etc/grafana/provisioning
    environment: 
      <<: *common-postgres-variables
      <<: *common-influx-variables
    depends_on: 
      - postgres
      - influx
  postgres:
    build: ./postgres
    environment: *common-postgres-variables
    volumes: 
      - postgres_data:/var/lib/postgresql/data
  influx:
    image: influxdb
    ports:
        - 8086:8086
    environment: *common-influx-variables
    volumes:
      - influx_data:/var/lib/influxdb
  postREST:
    image: postgrest/postgrest
    ports: 
      - 5436:3000
    environment:
      - PGRST_DB_URI=postgres://postgres:mysecretpassword@postgres/smartfactory
      - PGRST_DB_ANON_ROLE=postgres
    depends_on: 
      - postgres

volumes:
  grafana_plugins:
  grafana_provisioning:
  postgres_data:
  influx_data:
